### ISSUE TITLE
No support for Vine UK

### ISSUE THREAD

**Issue by caisamuels** [Amazon-Vine-Explorer/AmazonVineExplorer#13]
There is no support for amazon.co.uk

**Comment by MarkusSR1984** [comment]
Thanks for your report.
can u plese try if it is working with the online dev version ?: [https://github.com/Amazon-Vine-Explorer/AmazonVineExplorer/raw/main/VineExplorerOnlineDevelopmentPreview.user.js](https://github.com/Amazon-Vine-Explorer/AmazonVineExplorer/raw/main/VineExplorerOnlineDevelopmentPreview.user.js)

But, as there is no localisation/translation included atm. the most messages etc will be in german.
Localisation is on our to do list, but i hope u can use our script until i have written the translation system.

**Comment by caisamuels** [comment]
I don’t think it will work because the link is Amazon.co.uk not .com

**Comment by MarkusSR1984** [comment]
Well, sorry, i used the wrong link.

Plese use [https://github.com/Amazon-Vine-Explorer/AmazonVineExplorer/raw/dev-main/VineExplorerOnlineDevelopmentPreview.user.js](https://github.com/Amazon-Vine-Explorer/AmazonVineExplorer/raw/dev-main/VineExplorerOnlineDevelopmentPreview.user.js) instead

**Comment by MarkusSR1984** [comment]
@caisamuels Can u please tell me if the dev version is working with the uk site ?
