### ISSUE TITLE
[Suggestion] Only run script within Vine area

### ISSUE THREAD

**Issue by DonBonRon** [Amazon-Vine-Explorer/AmazonVineExplorer#19]
The script is currently running everywhere on amazon.de / amazon.com, which means that the release notes are always displayed at the bottom left. For example, if you want to write something in the Amazon customer service chat, the DIV hides the text field. It would be great if the script was only active within the Vine area (/vine), because I only need it there and usually just leave a tab with Vine open.
Nevertheless, many thanks for the development, it's already a great tool!

**Comment by Christof121** [comment]
Hey there,

the Script itselfs runs on all Amazon Pages atm, but just adds the Branding.
The Branding needs a rework in some form.
Will be on the ToDo

**Comment by Christof121** [comment]
A close button has been added to the branding.
There are ideas to extend the script, which requires the use on the Amazon main page.

Fixed here: https://github.com/Amazon-Vine-Explorer/AmazonVineExplorer/commit/7f9129fa56ee599372526e36e34f0da5e516b9a9

The script checks whether it is in the Vine area, if this is not the case it terminates itself.
The branding will be revised and adjusted in the future.
