### ISSUE TITLE
Export Database not working in 0.10.8.1

### ISSUE THREAD

**Issue by th62** [Amazon-Vine-Explorer/AmazonVineExplorer#23]
The Databseexport didn't work in the actual version under Firefox.

**Comment by Christof121** [comment]
Hey, can you share a little more information with us?
The best thing to do is to open the browser console (F12 or right-click -> Investigate) and look for an error message there.

**Comment by th62** [comment]
Hi Christof,

here is the error-log:

Somithing was going wrong while init database :'( 
Amazon-Vine-Explorer.user.js:987:17
     database 
moz-extension://9f8e6ca2-21f5-414b-b826-1af93cde1c5c/userscripts/Amazon-Vine-Explorer.user.js?id=0652c266-d916-4b4d-9326-14383e280b25:987
     DB_HANDLER 
moz-extension://9f8e6ca2-21f5-414b-b826-1af93cde1c5c/userscripts/Amazon-Vine-Explorer.user.js?id=0652c266-d916-4b4d-9326-14383e280b25:494
     window["__f__ltx0xs96.wh"]/< 
moz-extension://9f8e6ca2-21f5-414b-b826-1af93cde1c5c/userscripts/Amazon-Vine-Explorer.user.js?id=0652c266-d916-4b4d-9326-14383e280b25:985
     Rt https://www.amazon.de/vine/vine-items?queue=potluck:9
     window["__f__ltx0xs96.wh"]/< 
moz-extension://9f8e6ca2-21f5-414b-b826-1af93cde1c5c/userscripts/Amazon-Vine-Explorer.user.js?id=0652c266-d916-4b4d-9326-14383e280b25:1
     "__f__ltx0xs96.wh" 
moz-extension://9f8e6ca2-21f5-414b-b826-1af93cde1c5c/userscripts/Amazon-Vine-Explorer.user.js?id=0652c266-d916-4b4d-9326-14383e280b25:1
     Rt https://www.amazon.de/vine/vine-items?queue=potluck:9
     o https://www.amazon.de/vine/vine-items?queue=potluck:81
     <anonym> https://www.amazon.de/vine/vine-items?queue=potluck:82
     set https://www.amazon.de/vine/vine-items?queue=potluck:91
     <anonym> 
moz-extension://9f8e6ca2-21f5-414b-b826-1af93cde1c5c/userscripts/Amazon-Vine-Explorer.user.js?id=0652c266-d916-4b4d-9326-14383e280b25:1
     Rt https://www.amazon.de/vine/vine-items?queue=potluck:9
     p https://www.amazon.de/vine/vine-items?queue=potluck:77
     u https://www.amazon.de/vine/vine-items?queue=potluck:79
     send https://www.amazon.de/vine/vine-items?queue=potluck:79
     eo https://www.amazon.de/vine/vine-items?queue=potluck:17
     send https://www.amazon.de/vine/vine-items?queue=potluck:79
     <anonym> https://www.amazon.de/vine/vine-items?queue=potluck:83
     m https://www.amazon.de/vine/vine-items?queue=potluck:78
Uncaught (in promise) DB_HANDLER.add(): ConstraintError: A mutation 
operation in the transaction failed because a constraint was not 
satisfied.
Uncaught (in promise) DB_HANDLER.add(): ConstraintError: A mutation 
operation in the transaction failed because a constraint was not 
satisfied.
Uncaught (in promise) DB_HANDLER.add(): ConstraintError: A mutation 
operation in the transaction failed because a constraint was not 
satisfied. 2
Uncaught (in promise) DB_HANDLER.add(): ConstraintError: A mutation 
operation in the transaction failed because a constraint was not 
satisfied.
Uncaught (in promise) DB_HANDLER.add(): ConstraintError: A mutation 
operation in the transaction failed because a constraint was not 
satisfied.
Uncaught (in promise) DB_HANDLER.add(): ConstraintError: A mutation 
operation in the transaction failed because a constraint was not 
satisfied. 7
Uncaught (in promise) DB_HANDLER.add(): ConstraintError: A mutation 
operation in the transaction failed because a constraint was not 
satisfied. 2

Am 18.03.2024 08:59, schrieb Christof:

> Hey, can you share a little more information with us?
> The best thing to do is to open the browser console (F12 or right-click 
> -> Investigate) and look for an error message there.
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/Amazon-Vine-Explorer/AmazonVineExplorer/issues/23#issuecomment-2003139686
[2]

**Comment by th62** [comment]
So, today the explorer has completely stopped working.
I uninstalled it and then reinstalled it. Now the data export is working again, but the script is still reading in data, let's see how it looks in the future.

**Comment by th62** [comment]
The problem is back again :(
Where is the database stored? Maybe I can make a backup manually....

**Comment by Christof121** [comment]
The database is Stores in the Browser.
Press F12 Top Open the Developer Window, than  Go to Local storage. The Data is Stores under Index DB (or so).
The way can be different in every Brwoser.
Im not at my PC right now, so I cant  say if there is a export function in the browser.

**Comment by th62** [comment]
Thx.
I make it quick&dirty, using chatgpt:
modified export-funktion:
function exportDatabase() {
    console.log('Create Database Dump...');

var request = indexedDB.open("VineVoiceExplorer");

request.onsuccess = function(event) {
    var db = event.target.result;

    var transaction = db.transaction(["VineVoiceExplorer_Objects"], "readonly");

    var objectStore = transaction.objectStore("VineVoiceExplorer_Objects");

    var json_data = [];

    objectStore.openCursor().onsuccess = function(event) {
        var cursor = event.target.result;
        if (cursor) {
            json_data.push(cursor.value);
            cursor.continue();
        } else {
            exportToJSON(json_data);
        }
    };
};

}

function exportToJSON(data) {
    var json_string = JSON.stringify(data, null, 2);

    var blob = new Blob([json_string], { type: "application/json" });

    var url = URL.createObjectURL(blob);
    var a = document.createElement("a");
    a.href = url;
    a.download = "VineData.json";

    document.body.appendChild(a);
    a.click();

    document.body.removeChild(a);
    console.log('Database Dump saved.');
}

**Comment by Christof121** [comment]
It's great that you have found a workaround for the time being. However, unfortunately this does not solve the problem permanently.
Unfortunately, I have not been able to replicate the error so far.

The following information would be helpful.
Which browser is being used?
Which operating system?
If the error occurs again, please share a screenshot of the console output.

**Comment by th62** [comment]
W10 pro
Firefox 124.0.1 (64-Bit)
AddOns:
![addons](https://github.com/Amazon-Vine-Explorer/AmazonVineExplorer/assets/101192095/07a57f50-d3aa-4adf-94ff-baae27df5965)

**Comment by th62** [comment]
What I have also noticed is that no entries seem to be deleted from the database. My export file currently contains 23.238 entries, but only 18,833 are listed on Vine.
I have been observing this for a few days now, that the export file keeps growing.

**Comment by Christof121** [comment]
> What I have also noticed is that no entries seem to be deleted from the database. My export file currently contains 23.238 entries, but only 18,833 are listed on Vine. I have been observing this for a few days now, that the export file keeps growing.


The script deletes data, unless this has been changed by Markus, only after it is no longer found in the AutoScan after 5 full runs. If you use it relatively rarely, it will of course take longer until these runs have been completed.

Since the AutoScan has to be revised again, I think this will also solve the problem.

The database export probably does not work at the moment due to the size of the database, which leads to problems as it is currently integrated.

**Comment by th62** [comment]
Ak, ok, thx 4 the info.

**Comment by numericOverflow** [comment]
FYI, had this same issue, created a PR to fix

**Comment by Christof121** [comment]
https://github.com/Amazon-Vine-Explorer/AmazonVineExplorer/pull/31 was merged.
This will be fixed in the next Main release
