### ISSUE TITLE
Add "Mark Seen" button at bottom of last page in search results

### ISSUE THREAD

**Issue by numericOverflow** [Amazon-Vine-Explorer/AmazonVineExplorer#28]
**Feature Request:**  
It would be great to have the "Read" button (which marks current page seen and advances to next page) change function slightly on the last page of search results.  Since there is no next page, have it just switch to marking the current/final page seen and do nothing.

Right now, the Read button becomes inactive when there are no more pages, but I'm suggesting it just become a button that does the same as the "Mark Current Page Seen" button up at the top.  When you're paging through a bunch of results, it's nice to keep your mouse cursor in the same spot and having the button change automatically would be a nice speed addition.

![2024-03-26_122046](https://github.com/Amazon-Vine-Explorer/AmazonVineExplorer/assets/3429424/b342f9f8-f8f4-4cbf-849c-4a47373740e2)

**Comment by Christof121** [comment]
This is added in Version 0.10.8.5
